/*
 * This source file was generated by the Gradle 'init' task
 */
package me.rainma22.DuetMCP;

import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.lang.System.Logger;
import java.net.InetSocketAddress;
import java.nio.file.Path;
import java.text.MessageFormat;
import java.util.List;
import java.util.Map;
import me.rainma22.DuetMCP.Plugins.Plugin;
import me.rainma22.DuetMCP.Plugins.PluginManager;
import me.rainma22.DuetMCP.Tools.builtins.fetch.InternetFetchToolPlugin;
import me.rainma22.DuetMCP.Tools.ToolPlugin;
import me.rainma22.DuetMCP.Tools.builtins.time.TimeToolPlugin;
import me.rainma22.DuetMCP.Utils.ConfigurationManager;
import me.rainma22.DuetMCP.Utils.SessionManager;

public class DuetMCP {

    private static final Map DEFAULT_CONFIG = Map.of("port", 9090,
            "loadBuiltinTools", List.of(
                    InternetFetchToolPlugin.class.getCanonicalName(),
                    TimeToolPlugin.class.getCanonicalName()),
            "Session_maxConcurrentEntry", 512
    );

    public static void main(String[] args) throws IOException {
        Logger logger = System.getLogger(DuetMCP.class.getName());

        var conf = ConfigurationManager.ofClass(DuetMCP.class)
                .getConfig(DEFAULT_CONFIG);
        int port = conf.getInt("port");
        
        // set Session mapping size here
        var nSessionMapping = conf.getInt("Session_maxConcurrentEntry");
        SessionManager.setNumMappings(nSessionMapping);
        PluginManager.getInstance().loadPlugins(Path.of(".", "plugin"));

        for (var classname : conf.getJSONArray("loadBuiltinTools")) {
            if (classname == null) {
                continue;
            }
            logger.log(System.Logger.Level.INFO,
                    "loading " + classname.toString());
            try {
                Class<? extends Plugin> c = (Class<? extends Plugin>) ClassLoader.getSystemClassLoader()
                        .loadClass(classname.toString());
                c.getDeclaredConstructor()
                        .newInstance()
                        .onLoad();
                logger.log(System.Logger.Level.INFO,
                        "loaded " + classname.toString());
            } catch (Exception ex) {
                ex.printStackTrace();
                logger.log(Logger.Level.ERROR, new MessageFormat("{0}:\n\t Failed to load class {1}! \n ...skipping")
                        .format(new Object[]{ex, classname.toString()}));
            }
        }

        InetSocketAddress address = new InetSocketAddress(port);
        HttpServer server = HttpServer.create(address, 0);
        server.createContext("/mcp", new MCPHandler());
        server.setExecutor((r) -> Thread.ofVirtual().start(r));
        server.start();
        logger.log(Logger.Level.INFO, "server started on port: " + port);

    }

}
